### ISSUE TITLE
The code not working

### ISSUE THREAD

**Issue by suvm1998** [cypresssemiconductorco/mbed-os-example-wlan-offload-packet-filter#1]
**Prerequisites**

Can you reproduce the problem reliably?
Yes
Did you check current release notes for known issues?
Yes
If this is not the latest release, have you checked newer releases? 

**Description**:

**Steps to Reproduce:**

1. Forked the project and followed the instructions to run it on cy8ckit062wifibt board

2.At the try of run, the code was compiled n hex was generated successfully

3.Upon running the following error popped:
++ MbedOS Error Info ++
Error Status: 0x80010133 Code: 307 Module: 1
Error Message: Mutex: 0x8023C8C, Not allowed in ISR context
Location: 0x1002E041
Error Value: 0x8023C8C
Current Thread: <unnamed> Id: 0x0 Entry: 0xF9BAF000 StackSize: 0xB4058808 StackMem: 0xF3811889 SP: 0x8047594
For more info, visit: https://mbed.com/s/error?error=0x80010133&tgt=CY8CKIT_062_WIFI_BT
-- MbedOS Error Info --

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by cy-prasanthkumar** [comment]
This is working fine. I cloned this project. Built and programmed CY8CKIT-062-WIFI-BT kit.
[console_logs.txt](https://github.com/cypresssemiconductorco/mbed-os-example-wlan-offload-packet-filter/files/4840275/console_logs.txt)
